### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


а) Перемножить нельзя  
б) AB 2X3  
в) AB 8X8, BA 3X3  
г) АВ BA 4X4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A+B
=
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} 
+
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=$$

$$=
\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}
= 
\begin{pmatrix}
5 & -3\\ 
3 &  5
\end{pmatrix}$$

  $$AB
=
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
\cdot 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
=$$ 
$$=\begin{pmatrix}
1\cdot 4 + -2\cdot 0 & 1\cdot (-1) -2\cdot 5 \\ 
3\cdot 4 + 0\cdot 0 & 3\cdot (-1) + 0\cdot 5
\end{pmatrix} 
=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$

 $$BA
= 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
\cdot  
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
=$$
 $$=
\begin{pmatrix}
4\cdot 1 + -1\cdot 3 & 4\cdot (-2) + -1\cdot 0 \\ 
0\cdot 1 + 5\cdot 3 & 0\cdot (-2) + 5\cdot 0
\end{pmatrix}
= 
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]


In [2]:
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BА\n{np.dot(B, A)}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BА
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A-2B+4C=$$

$$\begin{pmatrix}
3 & 21\\ 
9 & -18\\
\end{pmatrix}
+
\begin{pmatrix}
0 & -10\\ 
-4 & 2\\
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\ 
4 & 4\\
\end{pmatrix}
=$$

$$
=
\begin{pmatrix}
3+0+8 & 21-10-16\\ 
9-4+4 & -18+2+4\\
\end{pmatrix}
=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [4]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


In [6]:
print(f'Матрица 𝐴*𝐴𝑇\n{np.dot(A,A.T)}')
print(f'Матрица 𝐴𝑇*𝐴\n{np.dot(A.T,A)}')

Матрица 𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица 𝐴𝑇*𝐴
[[45  0]
 [ 0 14]]


### Часть 2

__1.__ Вычислить определитель:

   a)

  $$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
  $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

  $$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

### Решение  
a) 
$$sin(x)\cdot sin(x) - cos(x)\cdot (-cos(x)) = sin^{2}(x) + cos^{2}(x) = 1$$ 

б)
$$ 4\cdot 5\cdot 9=180 $$

в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=$$
$$=7\cdot (12−15)−8\cdot (6−12)+9\cdot (5−8)=−21+48−27=0$$  

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2})=16$

б) $detA^{T}=detA=4$

в) $det(2A)=2^{n}detA=4\cdot 2^{n}$.

__3.__  Доказать, что матрица

 $$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


Строка 1 и 2 являются линейно зависимы $$ x_{2} = -2⋅x_{1} $$

__4.__ Найти ранг матрицы:

   а) 
    $$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$

 $$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix}$$

   б) 
    $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

 $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

In [7]:
import numpy as np

x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [8]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
c = [2, 3, 5, 6]

a = np.array([x, y, z, c])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
