In [1]:
import numpy as np
import matplotlib as plt

## №1. 
Решите линейную систему:
$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\end{array}
\right)\cdot \left(
\begin{array}{cccc}
x\\y\end{array}
\right) = \left(\begin{array}{cccc}
12\\2\\1\end{array}\right)
$

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1], float)
x = np.linalg.solve(A, B)
print(x)

[-9.2         0.9         6.46666667]


In [3]:
print(np.dot(A, x), B)

[12.  2.  1.] [12.  2.  1.]


## №2.
Найдите псевдорешение:

$x + 2y - z = 1$  
$3x - 4y = 7$  
$8x - 5y + 2z = 12$  
$2x - 5z = 7$  
$11x +4y - 7z = 15$

In [4]:
A = np.array([[1, 2, -1], [4, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.matrix_rank(A, 0.0001)

3

In [5]:
np.linalg.lstsq(A, B, rcond=None)

(array([ 1.14606774, -0.78531575, -0.83412346]),
 array([1.58475426]),
 3,
 array([15.45379715,  9.73365221,  3.52649521]))

## №3. 
Сколько решений имеет линейная система:
$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\end{array}
\right)\cdot \left(
\begin{array}{cccc}
x\\y\end{array}
\right) = \left(\begin{array}{cccc}
12\\2\\1\end{array}\right)
$

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([ 2.83726777e+16, -5.67453553e+16,  2.83726777e+16])

## №4.
Вычислите LU-разложение матрицы:

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
2 & 16 & 21\\
4 & 28 & 73\end{array}
\right)
$

In [7]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
np.linalg.det(A)

432.00000000000017

In [8]:
import scipy
import scipy.linalg
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]], float)
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
