# Задания на повторение материала 

### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = np.random.choice(a,(3, 3))
a1

array([[21, 17, 17],
       [21, 20, 17],
       [16, 12, 20]])

In [4]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(2, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
a5 = a.reshape(6, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a6 = a.reshape(12, 1)
a6

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a1 = a.reshape(12, -1)
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [10]:
a2 = a.reshape(6, -1)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a2 = a.reshape(4, -1)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a4 = a.reshape(-1, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a5 = a.reshape(-1, 4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет

### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 

### Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
a = np.random.randn(3,4)
a

array([[ 0.40159528, -0.61295427, -1.81884697, -0.57354645],
       [-1.04753833, -1.75062819,  0.41410736, -1.81450556],
       [ 2.4043394 , -1.13547373,  0.4731596 , -0.93199017]])

In [16]:
print(a.size)

12


In [17]:
a1 = a.flatten()
print(a1.size)

12


In [18]:
a1

array([ 0.40159528, -0.61295427, -1.81884697, -0.57354645, -1.04753833,
       -1.75062819,  0.41410736, -1.81450556,  2.4043394 , -1.13547373,
        0.4731596 , -0.93199017])

### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [24]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Мы расположили значения в двумерном массиве с помощью метода b.reshape.

a - одномерный массив, а b - двумерный массив