# Задания на повторение материала 

### Задание 1. 
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2.
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = np.random.choice(a,(3, 3))
a1

array([[20, 20, 16],
       [20, 17, 19],
       [14, 15, 12]])

In [4]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(2, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
a5 = a.reshape(6, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a6 = a.reshape(12, 1)
a6

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 3. 
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a1 = a.reshape(12, -1)
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [10]:
a2 = a.reshape(6, -1)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a2 = a.reshape(4, -1)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a4 = a.reshape(-1, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a5 = a.reshape(-1, 4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Задание 4. 
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [15]:
A = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
B = A.reshape (12, 1)

print("Размерность A: {}".format(A.ndim))
print("Размерность B: {}".format(B.ndim))

Размерность A: 1
Размерность B: 2


A.ndim не равно B.ndim

### Задание 5.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 

Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
a = np.random.randn(3,4)
a

array([[-0.72324186, -1.81356092, -0.26320561,  0.91367133],
       [ 0.33886713, -0.94640309,  0.5695    ,  0.09191643],
       [ 0.6389664 ,  0.8677186 , -0.48421399, -1.60680237]])

In [17]:
print(a.size)

12


In [18]:
a1 = a.flatten()
print(a1.size)

12


In [19]:
a1

array([-0.72324186, -1.81356092, -0.26320561,  0.91367133,  0.33886713,
       -0.94640309,  0.5695    ,  0.09191643,  0.6389664 ,  0.8677186 ,
       -0.48421399, -1.60680237])

### Задание 6.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [21]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Мы расположили значения в двумерном массиве с помощью метода b.reshape.

a - одномерный массив, а b - двумерный массив

### Задание 8.
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.  Итоговый массив v должен иметь атрибут size, равный 10.

In [22]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [23]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v.size

10

### Задание 9.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [26]:
a=np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [29]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [30]:
B.shape

(4, 4)

### Задание 10.
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [31]:
a = np.random.seed(42)

### Задание 11.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [32]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12.
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [33]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [34]:
D = B + C * 1
D

array([[ 11,  17,  35,  46],
       [ 24,  57,  98, 126],
       [ 29,  95, 151, 218],
       [ 42, 132, 219, 306]])

In [35]:
d = np.linalg.det(D)
d

-47196.0

In [36]:
r = np.linalg.matrix_rank(D)
r

4

In [37]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.13488431,  0.07958302,  0.17988813, -0.1812018 ],
       [-0.17149758,  0.14009662,  0.147343  , -0.13687601],
       [-0.05758963,  0.01220442, -0.20404272,  0.14899568],
       [ 0.09668192, -0.08009153,  0.05778032, -0.0194508 ]])

### Задание 13. 
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [38]:
D_inv = np.where (D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [39]:
print(B)
print(C)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [40]:
E = np.where(D_inv > 0, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])